#!/bin/bash
#
# Export Terraform Outputs to .env file
# Extracts S3 credentials and configuration from Terraform state
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/terraform"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/deploy/.env"

echo "📤 Exporting Terraform outputs to .env"
echo "====================================="
echo ""

# Check if terraform directory exists
if [ ! -d "$TERRAFORM_DIR" ]; then
    echo "❌ Terraform directory not found: $TERRAFORM_DIR"
    exit 1
fi

cd "$TERRAFORM_DIR"

# Check if terraform state exists
if [ ! -f "terraform.tfstate" ]; then
    echo "❌ Terraform state not found. Run 'infra/apply.sh' first"
    exit 1
fi

# Check if .env exists
if [ ! -f "$ENV_FILE" ]; then
    echo "⚠️  .env file not found, creating from example..."
    if [ -f "$PROJECT_ROOT/.env.prod.example" ]; then
        cp "$PROJECT_ROOT/.env.prod.example" "$ENV_FILE"
    else
        echo "❌ .env.prod.example not found"
        exit 1
    fi
fi

# Extract outputs
echo "📊 Reading Terraform outputs..."
S3_ENDPOINT=$(terraform output -raw s3_endpoint)
S3_REGION=$(terraform output -raw s3_region)
S3_BUCKET=$(terraform output -raw bucket_name)
S3_ACCESS_KEY_ID=$(terraform output -raw s3_access_key_id)
S3_SECRET_ACCESS_KEY=$(terraform output -raw s3_secret_access_key)
CDN_DOMAIN=$(terraform output -raw cdn_domain)

# Create temporary file with S3 variables
S3_VARS=$(cat <<EOF
S3_ENDPOINT=$S3_ENDPOINT
S3_REGION=$S3_REGION
S3_BUCKET=$S3_BUCKET
S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
S3_PUBLIC_BASE_URL=https://$CDN_DOMAIN
EOF
)

# Backup existing .env
cp "$ENV_FILE" "$ENV_FILE.backup"
echo "💾 Backed up existing .env to .env.backup"

# Remove old S3 variables if they exist
grep -v "^S3_" "$ENV_FILE" > "$ENV_FILE.tmp" || true
mv "$ENV_FILE.tmp" "$ENV_FILE"

# Append new S3 variables
echo "" >> "$ENV_FILE"
echo "# S3 Storage Configuration (auto-generated by Terraform)" >> "$ENV_FILE"
echo "$S3_VARS" >> "$ENV_FILE"

echo ""
echo "✅ S3 credentials added to $ENV_FILE"
echo ""
echo "📋 Variables added:"
echo "  S3_ENDPOINT=$S3_ENDPOINT"
echo "  S3_REGION=$S3_REGION"
echo "  S3_BUCKET=$S3_BUCKET"
echo "  S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID"
echo "  S3_SECRET_ACCESS_KEY=***hidden***"
echo "  S3_PUBLIC_BASE_URL=https://$CDN_DOMAIN"
echo ""
echo "⚠️  IMPORTANT: Configure DNS CNAME record:"
echo "  Name: $CDN_DOMAIN"
echo "  Type: CNAME"
echo "  Value: <CDN endpoint from Yandex Cloud Console>"
echo ""
echo "✅ Done!"
